php 8 null value deprecations
M1ke/easy-site-utils pull request #28
Opened 2023-04-19 14:08 UTC by craig-mcmahon

Fix null values being passed deprecations, and a couple of other fixes for php8

2023-04-19 14:09 UTC, craig-mcmahon commented
Not quite sure why the diff has gone so funny on a few files. Possibly due to some indentation changes

2023-04-25 09:03 UTC, M1ke requested changes

2023-04-25 09:03 UTC, M1ke commented on file.php
> +	if (empty($file)) {
Does this need to use `empty` or could it just be `!$file`?

2023-04-25 09:03 UTC, M1ke commented on math.php
> +	if (@strlen($number ?? '')>0){
We can likely remove the suppression too

2023-04-26 10:28 UTC, merged